set_property(GLOBAL APPEND PROPERTY ACORE_MODULE_TEST_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/test/AbstractWorldBotProgressorTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/AmbientTaskEligibilityTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/AmbientSpawnOverrideTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/CompanionFollowFormationTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/TravelWatchdogTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/WorldBotHotZoneTrackerTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/WorldBotMeleeHitBaselineTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/SimpleZonePopulationPlannerTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/SimplePartyRosterPlannerTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/PartyBotServiceTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/AccountAltRuntimeServiceTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/AccountAltRecoveryServiceTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/AccountAltRuntimeCoordinatorTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/AccountAltStartupRecoveryServiceTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/AccountAltDismissalServiceTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/AccountAltEquipmentSyncExecutorTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/AccountAltInventorySyncExecutorTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/AccountAltBankSyncExecutorTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/AccountAltItemRecoveryServiceTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/AccountAltSanityCheckerTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/BotCombatDoctrineResolverTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/BotCombatHealerDoctrineTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/SimpleBotCombatSpecRoleResolverTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/WorldBotAssignedGearFiltersTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/WorldBotAttackPowerBaselineTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/WorldBotBlockValueBaselineTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/WorldBotCriticalStrikeBaselineTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/WorldBotDefensiveCombatBaselineTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/WorldBotExpertiseBaselineTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/WorldBotGearBandTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/WorldBotHasteBaselineTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/WorldBotManaRegenBaselineTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/WorldBotPassiveSpellRulesTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/WorldBotPhysicalDamageBaselineTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/WorldBotPowerDefaultsTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/WorldBotPlayerStatBaselineTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/WorldBotPreparationServiceTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/WorldBotSpellCriticalStrikeBaselineTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/WorldBotSpellHitBaselineTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/WorldBotSpellPowerBaselineTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/WorldBotTalentAllocationRulesTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/WorldBotMaterializationIdentityTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/CharacterItemSnapshotClassifierTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/CharacterItemSanityCheckerTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test/LivingWorldCommandGrammarTest.cpp)

set_property(GLOBAL APPEND PROPERTY ACORE_MODULE_TEST_INCLUDES
  ${CMAKE_CURRENT_LIST_DIR}/src)
